package Secretaria;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentanaRegProfesor extends javax.swing.JFrame {

    private final String DB_URL = "jdbc:mysql://localhost:3306/sisinfo2bd"; // Cambia esto
    private final String DB_USER = "root"; // Cambia esto si tienes otro usuario
    private final String DB_PASSWORD = ""; // Cambia esto si tienes contraseña

    public VentanaRegProfesor() {
        initComponents();
        configurarTabla();
        cargarDatosDesdeBaseDeDatos();
        configurarEventosTabla();
    }

    private void configurarTabla() {
        String[] columnas = {"ID", "Nombre", "Carnet", "Domicilio", "Teléfono Fijo", "Teléfono Celular"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        jTable1.setModel(modelo);
    }

    private void cargarDatosDesdeBaseDeDatos() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            String sql = "SELECT ID_PROFESORES, NOMBREPROFESOR, CARNETPROFESOR, DOMICILIOPROFESOR, TELEFONOPROFESOR, CELULARPROFESOR FROM profesores";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                int id = rs.getInt("ID_PROFESORES");
                String nombre = rs.getString("NOMBREPROFESOR");
                String carnet = rs.getString("CARNETPROFESOR");
                String domicilio = rs.getString("DOMICILIOPROFESOR");
                String telefonoFijo = rs.getString("TELEFONOPROFESOR");
                String telefonoCelular = rs.getString("CELULARPROFESOR");

                modelo.addRow(new Object[]{id, nombre, carnet, domicilio, telefonoFijo, telefonoCelular});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
        }
    }

    private void configurarEventosTabla() {
        jTable1.getSelectionModel().addListSelectionListener(event -> {
            int filaSeleccionada = jTable1.getSelectedRow();
            if (filaSeleccionada >= 0) {
                jTextField1.setText(jTable1.getValueAt(filaSeleccionada, 1).toString());
                jTextField2.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
                jTextField3.setText(jTable1.getValueAt(filaSeleccionada, 3) != null ? jTable1.getValueAt(filaSeleccionada, 3).toString() : "");
                jTextField4.setText(jTable1.getValueAt(filaSeleccionada, 4) != null ? jTable1.getValueAt(filaSeleccionada, 4).toString() : "");
                jTextField5.setText(jTable1.getValueAt(filaSeleccionada, 5) != null ? jTable1.getValueAt(filaSeleccionada, 5).toString() : "");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        exitTxt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE PROFESORES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 6, -1, 46));

        jLabel2.setText("Nombre Completo del Profesor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 186, -1, -1));

        jLabel3.setText("Carnet o Identificación del Profesor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 220, -1, -1));

        jLabel4.setText("Domicilio del Profesor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 254, -1, -1));

        jLabel5.setText("Telefono Fijo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 288, -1, -1));

        jLabel6.setText("Telefono Celular:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 322, -1, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 414, 120, 47));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 414, 120, 47));

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 414, 120, 47));

        jButton4.setText("Añadir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 414, 120, 47));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 180, 258, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 214, 258, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 248, 258, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 282, 258, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 316, 258, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 70, 534, 104));

        exitTxt.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("< Atras");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });
        jPanel1.add(exitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel2.setBackground(new java.awt.Color(214, 227, 235));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 670, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int id = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            String nombre = jTextField1.getText();
            String carnet = jTextField2.getText();
            String domicilio = jTextField3.getText();
            String telefonoFijo = jTextField4.getText();
            String telefonoCelular = jTextField5.getText();

            try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
                String sql = "UPDATE profesores SET NOMBREPROFESOR=?, CARNETPROFESOR=?, DOMICILIOPROFESOR=?, TELEFONOPROFESOR=?, CELULARPROFESOR=? WHERE ID_PROFESORES=?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, nombre);
                pstmt.setString(2, carnet);
                pstmt.setString(3, domicilio);
                pstmt.setString(4, telefonoFijo);
                pstmt.setString(5, telefonoCelular);
                pstmt.setInt(6, id);

                int filasActualizadas = pstmt.executeUpdate();
                if (filasActualizadas > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Registro actualizado correctamente");
                    cargarDatosDesdeBaseDeDatos();
                }
            } catch (SQLException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar datos: " + e.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un profesor para modificar.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTable1.getSelectedRow();

    if (filaSeleccionada >= 0) {
        int idProfesor = (int) jTable1.getValueAt(filaSeleccionada, 0);

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de que deseas eliminar este profesor?", 
            "Confirmar eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
                conn.setAutoCommit(false); // Desactivar autocommit para asegurar la transacción

                // 1️⃣ Eliminar registros relacionados en horarios_profesores
                String sqlHorarios = "DELETE FROM horarios_profesores WHERE ID_PROFESORES = ?";
                try (PreparedStatement pstmtHorarios = conn.prepareStatement(sqlHorarios)) {
                    pstmtHorarios.setInt(1, idProfesor);
                    pstmtHorarios.executeUpdate();
                }

                // 2️⃣ Ahora eliminar al profesor
                String sqlProfesor = "DELETE FROM profesores WHERE ID_PROFESORES = ?";
                try (PreparedStatement pstmtProfesor = conn.prepareStatement(sqlProfesor)) {
                    pstmtProfesor.setInt(1, idProfesor);
                    int filasAfectadas = pstmtProfesor.executeUpdate();

                    if (filasAfectadas > 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Profesor eliminado exitosamente.");
                        conn.commit(); // Confirmar la transacción
                        cargarDatosDesdeBaseDeDatos(); // Actualizar la tabla
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el profesor.");
                        conn.rollback(); // Revertir cambios si algo falla
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un profesor para eliminar.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (!validarDatos()) return; // Detener el proceso si la validación falla

    String nombre = jTextField1.getText().trim();
    String carnet = jTextField2.getText().trim();
    String domicilio = jTextField3.getText().trim();
    String telefono = jTextField4.getText().trim();
    String celular = jTextField5.getText().trim();

    if (nombre.isEmpty() || carnet.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El nombre y el carnet son obligatorios.");
        return;
    }

    String usuario = nombre.replaceAll("\\s", "").substring(0, 5) + "005";
    String contrasena = nombre.split(" ")[0] + "005";

    try (Connection con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
        String sql = "INSERT INTO profesores (NOMBREPROFESOR, CARNETPROFESOR, DOMICILIOPROFESOR, TELEFONOPROFESOR, CELULARPROFESOR, USUARIO, CONTRASEÑA) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, nombre);
        ps.setString(2, carnet);
        ps.setString(3, domicilio.isEmpty() ? null : domicilio);
        ps.setString(4, telefono.isEmpty() ? null : telefono);
        ps.setString(5, celular.isEmpty() ? null : celular);
        ps.setString(6, usuario);
        ps.setString(7, contrasena);

        int filasAfectadas = ps.executeUpdate();
        if (filasAfectadas > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Profesor añadido correctamente.");
            cargarDatosDesdeBaseDeDatos();
            limpiarCampos();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al añadir profesor.");
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error de base de datos: " + ex.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de salir del sistema?", "Colegio X", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            VentanaPrincipalSec newframe = new VentanaPrincipalSec();
            newframe.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitTxt.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitTxt.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

     /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new VentanaRegProfesor().setVisible(true));
    }

    private void limpiarCampos() {
    jTextField1.setText("");  // Nombre
    jTextField2.setText("");  // Carnet
    jTextField3.setText("");  // Domicilio
    jTextField4.setText("");  // Teléfono Fijo
    jTextField5.setText("");  // Teléfono Celular
}
    private boolean validarDatos() {
    String telefonoFijo = jTextField4.getText().trim();
    String telefonoCelular = jTextField5.getText().trim();

    // Validación de teléfono fijo
    if (!telefonoFijo.isEmpty() && !telefonoFijo.matches("\\d{7}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El teléfono fijo debe tener exactamente 7 dígitos.");
        return false;
    }

    // Validación de teléfono celular
    if (!telefonoCelular.isEmpty() && !telefonoCelular.matches("\\d{8}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El teléfono celular debe tener exactamente 8 dígitos.");
        return false;
    }

    return true;
}


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}

